# Site wide configuration
# TEB: For local development, acess at http://0.0.0.0:4000/

title: OpenVnmrJ
description: "Open source software for nuclear magnetic resonance (NMR) spectroscopy and magnetic resonance imaging (MRI)"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
#url: //openvnmrj.github.io
port: 4000
base-url:    /

# Jekyll configuration


sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
  input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap
collections:
  documentation:
    output: true
    permalink: /:path/


# Site owner
owner:
  name: OpenVnmrJ
  web: http://openvnmrj.org
  email: eric.paulson@yale.edu
  twitter: 
  bio: "Open Source NMR Software"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
